# Theming
font: Hack 12
background: "#282828d0"
color: "#fbf1c7"
border: "#8ec07c"
separator: " ➜ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

menu:
  "a":
    desc: Applications
    submenu:
      "a": { desc: anki,      cmd: anki }
      "c": { desc: chromium,  cmd: chromium }
      "d": { desc: vesktop,   cmd: vesktop }
      "i": { desc: spotify,   cmd: spotify }
      "l": { desc: librewolf, cmd: librewolf }
      "p": { desc: keepassxc, cmd: keepassxc }
      "r": { desc: renoise,   cmd: renoise --scripting-dev }
      "s": { desc: steam,     cmd: steam }
  "p":
    desc: Programs
    submenu:
      "b": { desc: btop, cmd: alacritty -e btop }
  "m":
    desc: Mullvad
    submenu:
      "d": { desc: disconnect, cmd: mullvad disconnect; mullvad auto-connect set off }
      "c": { desc: connect,    cmd: mullvad connect; mullvad auto-connect set on }
  "c":
    desc: Controls
    submenu:
      "n": { desc: playerctl-next, cmd: playerctl next }
      "p": { desc: playerctl-prev, cmd: playerctl previous }
  "n":
    desc: Network
    submenu:
      "s": { desc: rescan, cmd: nmcli device wifi rescan }
  "t":
    desc: TTS
    submenu:
      "t": { desc: start, cmd: text-to-speech-clipboard.sh }
      "s": { desc: stop,  cmd: pkill -f espeak-ng }
  "!":
    desc: Power
    submenu:
      "h": { desc: Hibernate, cmd: systemctl hibernate }
      "R": { desc: Reboot,    cmd: reboot }
      "S": { desc: Shutdown,  cmd: shutdown }
